Name: Karan Bhatiya
Student ID: A20424290
Course Number: CS512
Semester: Fall 18

In [49]:
import numpy as np
# A

A = np.matrix([[1],[2],[3]])
B = np.matrix([[4],[5],[6]])
C = np.matrix([[-1],[1],[3]])

In [13]:
# A.1. 2A - B

print(2*A - B)

[[-2]
 [-1]
 [ 0]]


In [26]:
# A.2. ||A|| and the angle of A relative to the positive X axis

modA = np.sqrt(A.item((0,0))*A.item((0,0)) + A.item((1,0))*A.item((1,0)) + A.item((2,0))*A.item((2,0)))
rad = np.arccos(1/modA)
deg = np.rad2deg(rad)
print(modA, deg)


(3.7416573867739413, 74.498640433063)


In [27]:
# A.3. A, unit vector in the direction of A 

unitvector = (A.item((0,0))/modA, A.item((1,0))/modA, A.item((2,0))/modA)
print(unitvector)

(0.2672612419124244, 0.5345224838248488, 0.8017837257372732)


In [28]:
# A.4. the direction cosine of A

radx = np.arccos(A.item((0,0))/modA)
rady = np.arccos(A.item((1,0))/modA)
radz = np.arccos(A.item((2,0))/modA)

print(np.rad2deg(radx), np.rad2deg(rady), np.rad2deg(radz))

(74.498640433063, 57.688466762576155, 36.69922520048988)


In [24]:
# A.5. A.B and B.A

AB = A.item((0,0))*B.item((0,0)) + A.item((1,0))*B.item((1,0)) + A.item((2,0))*B.item((2,0))
BA = B.item((0,0))*A.item((0,0)) + B.item((1,0))*A.item((1,0)) + B.item((2,0))*A.item((2,0))

print(AB, BA)

(32, 32)


In [29]:
# A.6 the angle between A and B

modB = np.sqrt(B.item((0,0))*B.item((0,0)) + B.item((1,0))*B.item((1,0)) + B.item((2,0))*B.item((2,0)))
cos = np.arccos(AB/(modA*modB))
ang = np.rad2deg(cos)

print(ang)


12.933154491899135


In [47]:
# A.8. A*B and B*A

A1 = [1,2,3]
B1 = [4,5,6]
ABcross = np.cross(A1, B1)
BAcross = np.cross(B1, A1)

print(ABcross, BAcross)

(array([-3,  6, -3]), array([ 3, -6,  3]))


In [35]:
# A.9. A vector which is perpendicular to both A and B

u = ABcross/(np.linalg.norm(ABcross))
print(u)

[-0.40824829  0.81649658 -0.40824829]


In [39]:
# A.10. Linear dependency between A, B, C

l = np.matrix([[1,4,-1],[2,5,1],[3,6,3]])
print(l)
lnorm = np.linalg.det(l)
print(lnorm)

[[ 1  4 -1]
 [ 2  5  1]
 [ 3  6  3]]
1.9984014443252774e-15


In [84]:
# A.11. ATB and ABT

AT = np.transpose(A)

ATB = AT*(B)
print(ATB)
BT = np.transpose(B)

ABT = A*(BT)

print(ABT)

[[-4 13]
 [ 0  6]]
[[-2  8]
 [ 2  4]]


In [65]:
#B

A = np.matrix([[1,2,3],[4,-2,3],[0,5,-1]])
B = np.matrix([[1,2,1],[2,1,-4],[3,-2,1]])
C = np.matrix([[1,2,3],[4,5,6],[-1,1,3]])
print(A)
print(B)
print(C)

[[ 1  2  3]
 [ 4 -2  3]
 [ 0  5 -1]]
[[ 1  2  1]
 [ 2  1 -4]
 [ 3 -2  1]]
[[ 1  2  3]
 [ 4  5  6]
 [-1  1  3]]


In [55]:
# B.1. 2A - B

ans = 2*A - B
print(ans)

[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


In [56]:
# B.2. AB and BA

AB = A.dot(B)
print(AB)
BA = B.dot(A)
print(BA)

[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [59]:
# B.3. (AB)T and BTAT

ABtranspose = np.transpose(AB)
print(ABtranspose)

BT = np.transpose(B)
AT = np.transpose(A)
BtransposeAtranspose = BT.dot(AT)
print(BtransposeAtranspose)

[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [67]:
# B.4. |A| and |C|

Adet = np.linalg.det(A)
print(Adet)

Cdet = np.linalg.det(C)
print(Cdet)

54.999999999999964
7.494005416219837e-16


In [ ]:
# B.5. The matrix (A,B or C) in which the row vectors form an orthogonal


In [69]:
# B.6. A^-1 and B^-1

Ainv = np.linalg.inv(A)
print(Ainv)
Binv = np.linalg.inv(B)
print(Binv)

[[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
[[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [70]:
#C

A = np.matrix([[1,2],[3,2]])
B = np.matrix([[2,-2],[-2,5]])
print(A)
print(B)

[[1 2]
 [3 2]]
[[ 2 -2]
 [-2  5]]


In [81]:
# C.1. The eigenvalues and corresponding eigenvectors of A

w, v= np.linalg.eig(A)
print(w)
print(v)

[-1.  4.]
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [78]:
# C.2. The matrix V^-1AV where V is composed of eigenvectors of A

Vinv = np.linalg.inv(v)
print(Vinv*A*v)

[[-1.0000000e+00 -4.4408921e-16]
 [ 0.0000000e+00  4.0000000e+00]]


In [79]:
# C.3. Dot product between eigenvectors of A

v1 = v.item((0,0))*v.item((0,1)) + v.item((1,0))*v.item((1,1))
print(v1)

-0.196116135138


In [80]:
# C.4. Dot product between eigenvectors of B

w, v= np.linalg.eig(B)
print(w)
print(v)
v1 = v.item((0,0))*v.item((0,1)) + v.item((1,0))*v.item((1,1))
print(v1)

[1. 6.]
[[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]
0.0
